-- ELECTRONICS (25 Items)
INSERT INTO products (name, category, description, price, stock) VALUES ('iPhone 15 Pro', 'Electronics', 'Apple flagship smartphone', 1200000, 10);
INSERT INTO products (name, category, description, price, stock) VALUES ('Dell Latitude E6440', 'Electronics', 'Business class laptop', 250000, 5);
INSERT INTO products (name, category, description, price, stock) VALUES ('MacBook Air M2', 'Electronics', 'Thin and light laptop', 950000, 8);
INSERT INTO products (name, category, description, price, stock) VALUES ('Samsung S24 Ultra', 'Electronics', 'Android flagship phone', 1100000, 12);
INSERT INTO products (name, category, description, price, stock) VALUES ('Sony WH-1000XM5', 'Electronics', 'Noise canceling headphones', 350000, 15);
INSERT INTO products (name, category, description, price, stock) VALUES ('iPad Pro 12.9', 'Electronics', 'Powerful tablet for pros', 850000, 7);
INSERT INTO products (name, category, description, price, stock) VALUES ('Nintendo Switch', 'Electronics', 'Portable gaming console', 280000, 20);
INSERT INTO products (name, category, description, price, stock) VALUES ('GoPro Hero 12', 'Electronics', 'Action camera', 420000, 10);
INSERT INTO products (name, category, description, price, stock) VALUES ('Kindle Paperwhite', 'Electronics', 'E-book reader', 95000, 30);
INSERT INTO products (name, category, description, price, stock) VALUES ('Apple Watch Series 9', 'Electronics', 'Smartwatch', 450000, 15);
INSERT INTO products (name, category, description, price, stock) VALUES ('PS5 Console', 'Electronics', 'Next-gen gaming', 650000, 5);
INSERT INTO products (name, category, description, price, stock) VALUES ('Xbox Series X', 'Electronics', 'Powerful console', 620000, 6);
INSERT INTO products (name, category, description, price, stock) VALUES ('Canon EOS R6', 'Electronics', 'Mirrorless camera', 1800000, 3);
INSERT INTO products (name, category, description, price, stock) VALUES ('Bose SoundLink', 'Electronics', 'Bluetooth speaker', 120000, 25);
INSERT INTO products (name, category, description, price, stock) VALUES ('Samsung 4K Monitor', 'Electronics', '32-inch display', 320000, 10);
INSERT INTO products (name, category, description, price, stock) VALUES ('Logitech MX Master 3', 'Electronics', 'Professional mouse', 85000, 40);
INSERT INTO products (name, category, description, price, stock) VALUES ('Razer BlackWidow', 'Electronics', 'Mechanical keyboard', 110000, 15);
INSERT INTO products (name, category, description, price, stock) VALUES ('Asus ROG Phone 8', 'Electronics', 'Gaming smartphone', 980000, 8);
INSERT INTO products (name, category, description, price, stock) VALUES ('Google Pixel 8', 'Electronics', 'Pure Android phone', 750000, 12);
INSERT INTO products (name, category, description, price, stock) VALUES ('Nikon Z6 II', 'Electronics', 'Full-frame camera', 1650000, 4);
INSERT INTO products (name, category, description, price, stock) VALUES ('HP Spectre x360', 'Electronics', '2-in-1 Laptop', 880000, 6);
INSERT INTO products (name, category, description, price, stock) VALUES ('Seagate 2TB Drive', 'Electronics', 'External storage', 65000, 50);
INSERT INTO products (name, category, description, price, stock) VALUES ('Netgear Nighthawk', 'Electronics', 'WiFi 6 Router', 180000, 10);
INSERT INTO products (name, category, description, price, stock) VALUES ('Fitbit Charge 6', 'Electronics', 'Fitness tracker', 130000, 20);
INSERT INTO products (name, category, description, price, stock) VALUES ('Nvidia RTX 4080', 'Electronics', 'Graphics card', 1200000, 2);

-- ACCESSORIES (25 Items)
INSERT INTO products (name, category, description, price, stock) VALUES ('USB-C Hub', 'Accessories', '7-in-1 Adapter', 25000, 100);
INSERT INTO products (name, category, description, price, stock) VALUES ('Laptop Sleeve', 'Accessories', 'Waterproof 14 inch', 12000, 80);
INSERT INTO products (name, category, description, price, stock) VALUES ('Phone Stand', 'Accessories', 'Aluminum adjustable', 8500, 150);
INSERT INTO products (name, category, description, price, stock) VALUES ('Screen Protector', 'Accessories', 'Tempered glass', 5000, 500);
INSERT INTO products (name, category, description, price, stock) VALUES ('Power Bank 20k', 'Accessories', 'Fast charging', 45000, 60);
INSERT INTO products (name, category, description, price, stock) VALUES ('HDMI 2.1 Cable', 'Accessories', 'High speed 4K', 7500, 200);
INSERT INTO products (name, category, description, price, stock) VALUES ('Mouse Pad XXL', 'Accessories', 'Extended desk mat', 15000, 40);
INSERT INTO products (name, category, description, price, stock) VALUES ('Webcam 1080p', 'Accessories', 'HD video calls', 35000, 30);
INSERT INTO products (name, category, description, price, stock) VALUES ('Laptop Stand', 'Accessories', 'Ergonomic riser', 18000, 50);
INSERT INTO products (name, category, description, price, stock) VALUES ('AirTags 4-Pack', 'Accessories', 'Item trackers', 120000, 10);
INSERT INTO products (name, category, description, price, stock) VALUES ('Lightning Cable', 'Accessories', 'MFi Certified', 8000, 300);
INSERT INTO products (name, category, description, price, stock) VALUES ('Bluetooth Adapter', 'Accessories', 'USB dongle', 6500, 120);
INSERT INTO products (name, category, description, price, stock) VALUES ('MicroSD 128GB', 'Accessories', 'Ultra high speed', 14000, 100);
INSERT INTO products (name, category, description, price, stock) VALUES ('Cleaning Kit', 'Accessories', 'Screen and lens', 4500, 250);
INSERT INTO products (name, category, description, price, stock) VALUES ('Headphone Stand', 'Accessories', 'Wooden finish', 12500, 40);
INSERT INTO products (name, category, description, price, stock) VALUES ('Ring Light', 'Accessories', 'For streaming', 22000, 35);
INSERT INTO products (name, category, description, price, stock) VALUES ('Stylus Pen', 'Accessories', 'For touchscreens', 15000, 60);
INSERT INTO products (name, category, description, price, stock) VALUES ('Camera Bag', 'Accessories', 'Padded backpack', 45000, 20);
INSERT INTO products (name, category, description, price, stock) VALUES ('Car Charger', 'Accessories', 'Dual USB port', 7500, 150);
INSERT INTO products (name, category, description, price, stock) VALUES ('Ethernet Cable 5m', 'Accessories', 'Cat 6 reliable', 5500, 100);
INSERT INTO products (name, category, description, price, stock) VALUES ('External SSD Case', 'Accessories', 'NVMe to USB', 18000, 40);
INSERT INTO products (name, category, description, price, stock) VALUES ('Cooling Pad', 'Accessories', 'Laptop cooler', 16000, 50);
INSERT INTO products (name, category, description, price, stock) VALUES ('Wireless Presenter', 'Accessories', 'Laser pointer', 20000, 25);
INSERT INTO products (name, category, description, price, stock) VALUES ('Wrist Rest', 'Accessories', 'Memory foam', 9500, 80);
INSERT INTO products (name, category, description, price, stock) VALUES ('Green Screen', 'Accessories', 'Portable backdrop', 55000, 15);

-- FURNITURE (25 Items)
INSERT INTO products (name, category, description, price, stock) VALUES ('Ergonomic Chair', 'Furniture', 'Executive lumbar support', 180000, 12);
INSERT INTO products (name, category, description, price, stock) VALUES ('Standing Desk', 'Furniture', 'Electric height adj', 320000, 8);
INSERT INTO products (name, category, description, price, stock) VALUES ('Gaming Desk', 'Furniture', 'Z-shaped with LED', 150000, 15);
INSERT INTO products (name, category, description, price, stock) VALUES ('Bookshelf', 'Furniture', '5-tier oak wood', 85000, 20);
INSERT INTO products (name, category, description, price, stock) VALUES ('Office Sofa', 'Furniture', 'Modern leather 2-seat', 450000, 5);
INSERT INTO products (name, category, description, price, stock) VALUES ('File Cabinet', 'Furniture', '3-drawer locking', 65000, 18);
INSERT INTO products (name, category, description, price, stock) VALUES ('Desk Lamp', 'Furniture', 'LED with wireless charge', 25000, 40);
INSERT INTO products (name, category, description, price, stock) VALUES ('Side Table', 'Furniture', 'Minimalist metal', 35000, 25);
INSERT INTO products (name, category, description, price, stock) VALUES ('Rug 5x7', 'Furniture', 'Abstract pattern', 95000, 10);
INSERT INTO products (name, category, description, price, stock) VALUES ('Monitor Arm', 'Furniture', 'Single gas spring', 45000, 30);
INSERT INTO products (name, category, description, price, stock) VALUES ('Bean Bag', 'Furniture', 'Large memory foam', 55000, 15);
INSERT INTO products (name, category, description, price, stock) VALUES ('Floor Lamp', 'Furniture', 'Modern tripod design', 75000, 12);
INSERT INTO products (name, category, description, price, stock) VALUES ('Coffee Table', 'Furniture', 'Round glass top', 120000, 8);
INSERT INTO products (name, category, description, price, stock) VALUES ('Wall Mirror', 'Furniture', 'Full length gold frame', 85000, 10);
INSERT INTO products (name, category, description, price, stock) VALUES ('Shoe Rack', 'Furniture', '4-tier bamboo', 28000, 30);
INSERT INTO products (name, category, description, price, stock) VALUES ('Armchair', 'Furniture', 'Velvet accent chair', 145000, 10);
INSERT INTO products (name, category, description, price, stock) VALUES ('Drafting Table', 'Furniture', 'Adjustable angle', 110000, 6);
INSERT INTO products (name, category, description, price, stock) VALUES ('Ottoman', 'Furniture', 'Storage footstool', 42000, 20);
INSERT INTO products (name, category, description, price, stock) VALUES ('TV Stand', 'Furniture', 'Up to 65-inch', 165000, 7);
INSERT INTO products (name, category, description, price, stock) VALUES ('Coat Rack', 'Furniture', 'Standing wooden', 22000, 25);
INSERT INTO products (name, category, description, price, stock) VALUES ('Storage Cube', 'Furniture', 'Modular organizer', 18000, 50);
INSERT INTO products (name, category, description, price, stock) VALUES ('Nested Tables', 'Furniture', 'Set of 3', 68000, 15);
INSERT INTO products (name, category, description, price, stock) VALUES ('Dining Table', 'Furniture', '4-seater marble', 380000, 4);
INSERT INTO products (name, category, description, price, stock) VALUES ('Bar Stool', 'Furniture', 'Swivel industrial', 48000, 12);
INSERT INTO products (name, category, description, price, stock) VALUES ('Nightstand', 'Furniture', '2-drawer white', 32000, 20);

-- KITCHEN & HOME (25 Items)
INSERT INTO products (name, category, description, price, stock) VALUES ('Espresso Machine', 'Kitchen', '15-bar pressure', 280000, 10);
INSERT INTO products (name, category, description, price, stock) VALUES ('Air Fryer', 'Kitchen', '5L Digital XXL', 110000, 25);
INSERT INTO products (name, category, description, price, stock) VALUES ('Blender', 'Kitchen', '1000W High power', 75000, 20);
INSERT INTO products (name, category, description, price, stock) VALUES ('Rice Cooker', 'Kitchen', '10-cup capacity', 45000, 30);
INSERT INTO products (name, category, description, price, stock) VALUES ('Knife Set', 'Kitchen', '12pc Stainless steel', 55000, 15);
INSERT INTO products (name, category, description, price, stock) VALUES ('Electric Kettle', 'Kitchen', '1.7L Glass body', 28000, 40);
INSERT INTO products (name, category, description, price, stock) VALUES ('Toaster', 'Kitchen', '4-slice wide slot', 35000, 20);
INSERT INTO products (name, category, description, price, stock) VALUES ('Stand Mixer', 'Kitchen', '6-speed tilt head', 185000, 8);
INSERT INTO products (name, category, description, price, stock) VALUES ('Slow Cooker', 'Kitchen', 'Programmable 6-quart', 65000, 12);
INSERT INTO products (name, category, description, price, stock) VALUES ('Microwave', 'Kitchen', '900W Stainless', 95000, 15);
INSERT INTO products (name, category, description, price, stock) VALUES ('Coffee Grinder', 'Kitchen', 'Burr mill grinder', 32000, 25);
INSERT INTO products (name, category, description, price, stock) VALUES ('Juicer', 'Kitchen', 'Cold press masticating', 88000, 10);
INSERT INTO products (name, category, description, price, stock) VALUES ('Non-stick Pan Set', 'Kitchen', '3-piece ceramic', 42000, 30);
INSERT INTO products (name, category, description, price, stock) VALUES ('Bread Maker', 'Kitchen', 'Automatic 2lb loaf', 115000, 5);
INSERT INTO products (name, category, description, price, stock) VALUES ('Water Filter', 'Kitchen', 'Countertop system', 58000, 20);
INSERT INTO products (name, category, description, price, stock) VALUES ('Food Processor', 'Kitchen', '8-cup multifunction', 72000, 18);
INSERT INTO products (name, category, description, price, stock) VALUES ('Vacuum Sealer', 'Kitchen', 'With starter bags', 48000, 25);
INSERT INTO products (name, category, description, price, stock) VALUES ('Induction Cooktop', 'Kitchen', 'Single portable burner', 38000, 15);
INSERT INTO products (name, category, description, price, stock) VALUES ('Waffle Maker', 'Kitchen', 'Belgian style deep', 25000, 20);
INSERT INTO products (name, category, description, price, stock) VALUES ('Deep Fryer', 'Kitchen', 'Pro style stainless', 62000, 10);
INSERT INTO products (name, category, description, price, stock) VALUES ('Soda Maker', 'Kitchen', 'With 60L CO2', 92000, 12);
INSERT INTO products (name, category, description, price, stock) VALUES ('Cast Iron Skillet', 'Kitchen', 'Pre-seasoned 12-inch', 35000, 40);
INSERT INTO products (name, category, description, price, stock) VALUES ('Meat Grinder', 'Kitchen', 'Electric heavy duty', 110000, 7);
INSERT INTO products (name, category, description, price, stock) VALUES ('Dinnerware Set', 'Kitchen', '24-piece porcelain', 125000, 10);
INSERT INTO products (name, category, description, price, stock) VALUES ('Spice Rack', 'Kitchen', 'Rotating with 16 jars', 18000, 50);